from interpolation.interpolation import linear_interpolation
from interpolation.interpolation import linear_extrapolate
from interpolation.interpolation import interpolate_piece_line
from interpolation.interpolation import lagrange_interpolation_polynomial
from interpolation.graphs import draw_interpolate
from interpolation.graphs import draw_interpolate_piece_line
from interpolation.graphs import draw_lagranzh